services:
  djangoapp:
    container_name: app
    build: ./be
    ports:
      - "8000:8000"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=Ava2024
      - PG_DB=Ava2024
      - PG_HOST=db
      - PG_PORT=5432
    depends_on:
      - db
  db:
    container_name: dbAva
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ava2024
      - POSTGRES_DB=Ava2024
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  frontend:
    container_name: fe
    image: fe
    build:
      context: ./fe
    ports:
      - "3000:3000"
  nginx:
    container_name: nginx
    image: nginx:1.21.0-alpine
    build:
      context: ./nginx
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - djangoapp
      - frontend

volumes:
  pgdata: {}
